name: Build React Native Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > /tmp/my-release-key.keystore

      - name: Create keystore.properties
        run: |
          cat > android/keystore.properties << EOF
          storeFile=/tmp/my-release-key.keystore
          storePassword=${{ secrets.RELEASE_STORE_PASSWORD }}
          keyAlias=${{ secrets.RELEASE_KEY_ALIAS }}
          keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}
          EOF
          
          # Проверяем, что файл создался
          cat android/keystore.properties

      - name: Build Release APK
        run: |
          chmod +x ./android/gradlew
          cd android
          ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rocketchat-app-release
          path: android/app/build/outputs/apk/release/*.apk